App\Domain\Model\User\User:
    type: entity
    table: user
    repositoryClass: BenGorUser\DoctrineORMBridge\Infrastructure\Persistence\DoctrineORMUserRepository
    fields:
      facebookId:
        column: facebook_id
        type: guid
        nullable: true