App\Domain\Model\User\User:
    type: entity
    table: user
    repositoryClass: App\Infrastructure\Symfony\Framework\Repository\UserRepository
    lifecycleCallbacks: {  }
    embedded:
        facebookId:
            class: App\Domain\Model\User\UserFacebookId
        facebookAccessToken:
            class: App\Domain\Model\User\UserFacebookAccessToken
    manyToMany:
      usersFollowed:
        targetEntity: App\Domain\Model\User\User
        inversedBy: usersFollowMe
        joinTable:
          name: users_followed
          joinColumns:
            user_id:
              referencedColumnName: id
          inverseJoinColumns:
            user_followed_id:
              referencedColumnName: id
      usersFollowMe:
        targetEntity: App\Domain\Model\User\User
        mappedBy: usersFollowed
