version: '2'

networks:
  crv_dev_network:
    driver: bridge

services:
  db:
    container_name: mysql
    image: mysql:5.7.17
    env_file:
      - ./.env
    volumes:
      - "./volumes/mysql/database:/var/lib/mysql"
      - "./volumes/mysql/conf:/etc/mysql/conf.d"
    networks:
      crv_dev_network:
        aliases:
          - mysql
    ports:
      - "3306:3306"

  php:
    container_name: php
    build: docker/php
    volumes:
      - ./code:/app
      - ./volumes/logs:/app/var/logs
      - ./volumes/cache:/app/var/cache
    networks:
      crv_dev_network:
        aliases:
          - php
    env_file:
      - ./.env

  nginx:
    container_name: nginx
    build: docker/nginx
    volumes_from:
      - php
    ports:
      - "80:80"
    networks:
      crv_dev_network:
        aliases:
          - nginx