version: '3.2'

networks:
  crv_dev_network:
    driver: bridge

services:
  db:
    container_name: mysql
    image: mysql:5.7.17
    env_file:
      - ./.env
    volumes:
      - ./Docker/volumes/mysql/database:/var/lib/mysql
      - ./Docker/volumes/mysql/conf:/etc/mysql/conf.d
    networks:
      crv_dev_network:
        aliases:
          - mysql
    ports:
      - "3306:3306"

  app:
    container_name: symfony-app
    build:
      context: ./
      dockerfile: Dockerfile.prod
    volumes:
      - ./Docker/volumes/log/App:/app/App/var/log
      - ./Docker/volumes/cache/App:/app/App/var/cache
      - ./Docker/volumes/session/App:/app/App/var/sessions
      - ./Docker/volumes/log/CompositeUi:/app/CompositeUi/var/log
      - ./Docker/volumes/cache/CompositeUi:/app/CompositeUi/var/cache
      - ./Docker/volumes/session/CompositeUi:/app/CompositeUi/var/sessions
    networks:
      crv_dev_network:
        aliases:
          - php
    env_file:
      - ./.env

  nginx:
    container_name: nginx-server
    build:
      context: Docker/nginx
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    networks:
      crv_dev_network:
        aliases:
          - nginx