# This file is part of the Social Recipes.
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @author Ruben Garcia <ruben.garcia@opendeusto.es>

doctrine_migrations:
    dir_name: "%kernel.root_dir%/../../Persistence/Doctrine/Migrations"
    namespace: Recipes\Infrastructure\Persistence\Doctrine\Migrations
    table_name: recipes_migration_versions
    name: Recipes migrations

doctrine:
    dbal:
        driver: pdo_mysql
        host: "%database_host%"
        port: "%database_port%"
        dbname: "%database_name%"
        user: "%database_user%"
        password: "%database_password%"
        server_version: "%database_server_version%"
        charset: UTF8
        types:
          UserId:  Recipes\Infrastructure\Persistence\Doctrine\Domain\Type\User\UserIdType
          BookId:  Recipes\Infrastructure\Persistence\Doctrine\Domain\Type\Book\BookIdType
          CategoryId:  Recipes\Infrastructure\Persistence\Doctrine\Domain\Type\Category\CategoryIdType
          RecipeId:  Recipes\Infrastructure\Persistence\Doctrine\Domain\Type\Recipes\RecipeIdType
          StepId:  Recipes\Infrastructure\Persistence\Doctrine\Domain\Type\Recipes\StepIdType
          json_object: AurimasNiekis\DoctrineJsonObjectType\JsonObjectType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        mappings:
          CoreModels:
            mapping: true
            type: yml
            dir: "%kernel.root_dir%/../../Persistence/Doctrine/ORM/CoreModels"
            alias: 'CoreModels'
            prefix: 'Recipes\Domain\Model'
            is_bundle: false
          HelperModels:
            mapping: true
            type: yml
            dir: "%kernel.root_dir%/../../Persistence/Doctrine/ORM/HelperModels"
            alias: 'HelperModels'
            prefix: 'Recipes\Infrastructure\Persistence\Doctrine\Domain\Model'
            is_bundle: false
