
# This file is part of the Social Recipes.
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @author Ruben Garcia <ruben.garcia@opendeusto.es>

#Redirections to CompositeUI
app_home:
    path: /

recipes_index:
    path: /recipes/
    defaults:
        _controller: Recipes\Infrastructure\Symfony\HttpAction\IndexAction::__invoke
    methods:
        - GET

recipes_book_add:
    path: /recipes/book/
    defaults:
        _controller: Recipes\Infrastructure\Symfony\HttpAction\Book\AddAction::__invoke
    methods:
        - POST

recipes_book_get:
    path: /recipes/book/
    defaults:
        _controller: Recipes\Infrastructure\Symfony\HttpAction\Book\GetAction::__invoke
    methods:
        - GET

recipes_book_update:
    path: /recipes/book/
    defaults:
        _controller: Recipes\Infrastructure\Symfony\HttpAction\Book\UpdateAction::__invoke
    methods:
        - UPDATE

recipes_book_delete:
    path: /recipes/book/
    defaults:
        _controller: Recipes\Infrastructure\Symfony\HttpAction\Book\DeleteAction::__invoke
    methods:
        - DELETE

microservices_internal_authentication:
    resource: "@MicroservicesInternalAuthenticationBundle/Resources/config/routing.yml"
    prefix:   /
