# This file is part of the Social Recipes.
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @author Ruben Garcia <ruben.garcia@opendeusto.es>

security:
    providers:
        user_api_provider:
            id: Recipes\Infrastructure\Symfony\Security\Session\JWTUserProvider

    firewalls:
        main:
            anonymous: ~
            guard:
                authenticators:
                    - Recipes\Infrastructure\Symfony\Security\Session\JWTAuthenticator
            provider: user_api_provider

    access_control:
        - { path: ^/recipes/, roles: ROLE_USER }
