# This file is part of the Social Recipes.
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @author Ruben Garcia <ruben.garcia@opendeusto.es>

security:
    providers:
        user_api_provider:
            id: "fiser.microservices_internal_authentication.security.user_provider"

    firewalls:
        main:
            anonymous: ~
            guard:
                authenticators:
                    - "fiser.microservices_internal_authentication.security.authenticator"
            provider: user_api_provider

#    access_control:
#        - { path: ^/recipes/, roles: ROLE_USER }
