services:
    _defaults:
        autowire: false
        autoconfigure: true
        public: true


    Recipes\Infrastructure\Persistence\Doctrine\Domain\Events\Book\BookPostPersistEvent:
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    Recipes\Infrastructure\Persistence\Doctrine\Domain\Events\Category\CategoryPostPersistEvent:
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    Recipes\Infrastructure\Persistence\Doctrine\Domain\Events\User\UserPostPersistEvent:
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    Recipes\Infrastructure\Persistence\Doctrine\Domain\Events\Recipes\RecipePostPersistEvent:
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    Recipes\Infrastructure\Persistence\Doctrine\Domain\Events\Book\BookPostLoadEvent:
        tags:
            - { name: doctrine.event_listener, event: postLoad }

    Recipes\Infrastructure\Persistence\Doctrine\Domain\Events\Category\CategoryPostLoadEvent:
        tags:
            - { name: doctrine.event_listener, event: postLoad }

    Recipes\Infrastructure\Persistence\Doctrine\Domain\Events\Recipes\RecipePostLoadEvent:
        tags:
            - { name: doctrine.event_listener, event: postLoad }

    Recipes\Infrastructure\Persistence\Doctrine\Domain\Events\User\UserPostLoadEvent:
        tags:
            - { name: doctrine.event_listener, event: postLoad }
