services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Recipes\Infrastructure\Persistence\Doctrine\Domain\Model\Book\DoctrineBookRepository:
        class: Recipes\Infrastructure\Persistence\Doctrine\Domain\Model\Book\DoctrineBookRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Recipes\Domain\Model\Book\Book
    Recipes\Infrastructure\Persistence\Doctrine\Domain\Model\User\DoctrineUserRepository:
        class: Recipes\Infrastructure\Persistence\Doctrine\Domain\Model\User\DoctrineUserRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Recipes\Domain\Model\User\User
    Recipes\Infrastructure\Persistence\Doctrine\Domain\Model\Recipes\DoctrineRecipeRepository:
        class: Recipes\Infrastructure\Persistence\Doctrine\Domain\Model\Recipes\DoctrineRecipeRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Recipes\Domain\Model\Recipes\Recipe
    Recipes\Infrastructure\Persistence\Doctrine\Domain\Model\Category\DoctrineCategoryRepository:
        class: Recipes\Infrastructure\Persistence\Doctrine\Domain\Model\Category\DoctrineCategoryRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Recipes\Domain\Model\Category\Category
    Recipes\Infrastructure\Persistence\Sql\Domain\Model\Book\SqlBookRepository:
        class: Recipes\Infrastructure\Persistence\Sql\Domain\Model\Book\SqlBookRepository
        arguments:
            - '@lin3s.persistence.sql.pdo'
            - '@recipes.infrastructure.persistence.sql.domain.model.book.sql_book_hydrator'
    Recipes\Infrastructure\Persistence\Sql\Domain\Model\User\SqlUserRepository:
        class: Recipes\Infrastructure\Persistence\Sql\Domain\Model\User\SqlUserRepository
        arguments:
            - '@lin3s.persistence.sql.pdo'
            - '@recipes.infrastructure.persistence.sql.domain.model.user.sql_user_hydrator'
    Recipes\Infrastructure\Persistence\Sql\Domain\Model\Recipes\SqlRecipeRepository:
        class: Recipes\Infrastructure\Persistence\Sql\Domain\Model\Recipes\SqlRecipeRepository
        arguments:
            - '@lin3s.persistence.sql.pdo'
            - '@recipes.infrastructure.persistence.sql.domain.model.recipes.sql_recipe_hydrator'
    Recipes\Infrastructure\Persistence\Sql\Domain\Model\Category\SqlCategoryRepository:
        class: Recipes\Infrastructure\Persistence\Sql\Domain\Model\Category\SqlCategoryRepository
        arguments:
            - '@lin3s.persistence.sql.pdo'
            - '@recipes.infrastructure.persistence.sql.domain.model.category.sql_category_hydrator'

    Recipes\Domain\Model\Book\BookRepository: '@Recipes\Infrastructure\Persistence\Sql\Domain\Model\Book\SqlBookRepository'
    Recipes\Domain\Model\Category\CategoryRepository: '@Recipes\Infrastructure\Persistence\Sql\Domain\Model\Category\SqlCategoryRepository'
    Recipes\Domain\Model\Recipes\RecipeRepository: '@Recipes\Infrastructure\Persistence\Sql\Domain\Model\Recipes\SqlRecipeRepository'
    Recipes\Domain\Model\User\UserRepository: '@Recipes\Infrastructure\Persistence\Sql\Domain\Model\User\SqlUserRepository'