Recipes\Domain\Model\Book\Book:
  type: entity
  table: recipe_book
  repositoryClass: Recipes\Infrastructure\Persistence\Doctrine\Domain\Model\Book\DoctrineBookRepository
  id:
    id:
      column: id
      type: BookId

  embedded:
    scope:
      class: "Recipes\\Domain\\Model\\Scope"
  fields:
     owner:
       type: UserId
       column: owner_id

  oneToMany:
    translations:
      targetEntity: BookTranslation
      mappedBy: origin