Recipes\Domain\Model\Recipes\Step:
  type: entity
  table: recipe_step

  id:
    id:
      column: id
      type: StepId

  oneToMany:
    translations:
      targetEntity: StepTranslation
      mappedBy: origin
      cascade: ["persist"]

  manyToOne:
    recipe:
      targetEntity: Recipes\Domain\Model\Recipes\Recipe
      joinColumn:
        name: recipe_id
        referencedColumnName: id
        onDelete: cascade

  fields:
    ingredients:
      type: json_object
    tools:
      type: json_object