Session\Domain\Model\Session\User:
    type: entity
    table: user
    lifecycleCallbacks: {  }
    repositoryClass: BenGorUser\DoctrineORMBridge\Infrastructure\Persistence\DoctrineORMUserRepository
    embedded:
        facebookId:
            columnPrefix: facebook_id_
            class: Session\Domain\Model\Session\UserFacebookId
        facebookAccessToken:
            columnPrefix: facebook_access_token_
            class: Session\Domain\Model\Session\UserFacebookAccessToken
        fullName:
            columnPrefix: full_name_
            class: Session\Domain\Model\Session\FullName

    manyToMany:
      usersFollowed:
        fetch: EXTRA_LAZY
        targetEntity: Session\Domain\Model\Session\User
        inversedBy: usersFollowMe
        joinTable:
          name: users_followed
          joinColumns:
            user_id:
              onDelete: CASCADE
              referencedColumnName: id
          inverseJoinColumns:
            user_followed_id:
              onDelete: CASCADE
              referencedColumnName: id