# This file is part of the Php DDD Standard project.
#
# Copyright (c) 2017-present LIN3S <info@lin3s.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

security:
    providers:
        user_api_provider:
            id: CompositeUi\Infrastructure\Symfony\Security\Session\JWTUserProvider

    firewalls:
        main:
            anonymous: ~
            guard:
                authenticators:
                    - CompositeUi\Infrastructure\Symfony\Security\Session\JWTAuthenticator
            provider: user_api_provider