Recipes\Domain\Model\Book\Book:
  type: entity
  table: recipe_book
  lifecycleCallbacks: {  }
  id:
    id:
      column: id
      type: BookId

  embedded:
    scope:
      class: "Recipes\\Domain\\Model\\Scope"

  manyToOne:
    owner:
      targetEntity: "Recipes\\Domain\\Model\\User\\User"
      joinColumn:
        name: owner_id
        referencedColumnName: id

  oneToMany:
    translations:
      targetEntity: BookTranslation
      mappedBy: origin
