Recipes\Domain\Model\Book\Book:
  type: entity
  table: recipe_book
  lifecycleCallbacks: {  }
  id:
    id:
      column: id
      type: BookId

  embedded:
    scope:
      class: "Recipes\\Domain\\Model\\Scope"

  manyToOne:
    owner:
      targetEntity: "Recipes\\Domain\\Model\\User\\User"
      joinColumn:
        name: owner_id
        referencedColumnName: id

  manyToMany:
    follow:
      targetEntity: "Recipes\\Domain\\Model\\User\\User"
      joinTable:
        name: recipe_user_books
        joinColumns:
          book_id:
            referencedColumnName: id
        inverseJoinColumns:
          user_id:
            referencedColumnName: id
