Recipes\Domain\Model\Category\Category:
  type: entity
  table: recipe_category
  lifecycleCallbacks: {  }
  id:
    id:
      column: id
      type: CategoryId

  oneToMany:
    translations:
      targetEntity: CategoryTranslation
      mappedBy: origin

  manyToOne:
    parent:
      targetEntity: Category
      joinColumn:
        name: parent_id
        referencedColumnName: id
        inversedBy: children

  manyToMany:
    recipes:
      targetEntity: "Recipes\\Domain\\Model\\Recipes\\Recipe"
      joinTable:
        name: recipe_recipe_category
        inversedBy: categories
        joinColumns:
          category_id:
            referencedColumnName: id
        inverseJoinColumns:
          recipe_id:
            referencedColumnName: id
