Recipes\Domain\Model\Category\CategoryTranslation:
  type: entity
  table: recipe_category_translation
  id:
    origin:
      associationKey: true
    locale:
      type: string
  embedded:
    name:
      class: "Recipes\\Domain\\Model\\Name"