Recipes\Domain\Model\Recipes\Recipe:
  type: entity
  table: recipe_recipe

  id:
    id:
      column: id
      type: RecipeId

  embedded:
    scope:
      class: "Recipes\\Domain\\Model\\Scope"
    servings:
      class: "Recipes\\Domain\\Model\\Recipes\\Servings"
    time:
      class: "Recipes\\Domain\\Model\\Time"
    difficulty:
      class: "Recipes\\Domain\\Model\\Difficulty"

  fields:
    ingredients:
      type: json_object
    tools:
      type: json_object
    hashtags:
      type: json_object

  manyToOne:
    owner:
      targetEntity: "Recipes\\Domain\\Model\\User\\User"
      joinColumn:
        name: owner_id
        referencedColumnName: id