Recipes\Domain\Model\Recipes\RecipeTranslation:
  type: entity
  table: recipe_recipe_translation
  id:
    origin:
      associationKey: true
    locale:
      type: string
  embedded:
    title:
      class: "Recipes\\Domain\\Model\\Title"
    subtitle:
      class: "Recipes\\Domain\\Model\\Subtitle"
    description:
      class: "Recipes\\Domain\\Model\\Description"

  manyToOne:
    origin:
      targetEntity: "Recipes\\Domain\\Model\\Recipes\\Recipe"
      inversedBy: translations