# This file is part of the Social Recipes.
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @author Ruben Garcia <ruben.garcia@opendeusto.es>

#Redirections to CompositeUI
app_homepage:
    path: /

app_logged:
    path: /{_locale}/timeline

#Facebook url connections
oauth_facebook:
    path: /session/connect/facebook
    defaults:
        _controller: Session\Infrastructure\Symfony\HttpAction\Session\FacebookConnectAction:__invoke
    methods:
        - GET

oauth_facebook_check:
    path: /session/connect/facebook/check
    defaults:
        _controller: Session\Infrastructure\Symfony\HttpAction\Session\FacebookConnectCheckAction:__invoke
    methods:
        - GET
        - POST

#JWT URLs
session.http_action.session.jwt_decode:
    path: /session/user/decode
    defaults:
        _controller: Session\Infrastructure\Symfony\HttpAction\Session\JWTDecodeAction:__invoke
    methods:
        - GET
