# This file is part of the Php DDD Standard project.
#
# Copyright (c) 2017-present LIN3S <info@lin3s.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

app_home:
    path: /
    controller: "compositeui.http_action.home_action:__invoke"

app_timeline:
    path: /timeline
    controller: "compositeui.http_action.timeline_action:__invoke"
